name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: foundry-rs/foundry-toolchain@v1

      - name: forge build
        run: forge build --sizes

      - name: forge test
        run: forge test -vv
